steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/docker-repo/service-a:latest",
        "-f",
        "./service-a.Dockerfile",
        ".",
      ]
images:
  - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/docker-repo/service-a:latest"
